<?php

/**
 * @file
 * Contains block module functions.
 */

/**
 * Implements hook_theme().
 */
function capitalcamp_blocks_theme($existing, $type, $theme, $path) {
  return [
    'dgc_sponsors_by_level' => [
      'template' => 'dgc-sponsors-by-level',
      'variables' => [
        'sponsor_listing' => NULL,
        'sponsor_level' => NULL,
        'conference_year' => NULL,
      ],
    ],
    'dgc_proposed_sessions' => [
      'template' => 'dgc-proposed-sessions',
      'variables' => [
        'proposed_sessions' => NULL,
        'conference_year' => NULL,
      ],
    ],
    'dgc_sessionize' => [
      'template' => 'dgc-sessionize',
    ],
    'dgc_accepted_sessions' => [
      'template' => 'dgc-accepted-sessions',
      'variables' => [
        'accepted_sessions' => NULL,
        'conference_year' => NULL,
      ],
    ],
  ];
}
