version: 1.3.0
services:
  - mysql
  - composer:
      version: 2
  - php:
      version: 8.0

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer install --ansi
              - source ${BLT_DIR}/scripts/pipelines/setup_env
              - nvm install v14.17
              - npm install -g npm
        - validate:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/validate
        - setup-app:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/setup_app
        - tests:
            type: script
            script:
              - set -ev
              - export PATH=${COMPOSER_BIN}:${PATH}
              - blt tests --define drush.alias='${drush.aliases.ci}' -D behat.web-driver=chrome --no-interaction --ansi -vvv
              - set +v
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact
