<?php

/**
 * @file
 * Provides custom migration to content migration.
 */

/**
 * Implements hook_module_preuninstall().
 */
function wbm_to_cm_module_preuninstall($module) {
  if (\Drupal::isConfigSyncing()) {
    return;
  }
  elseif ($module == 'workbench_moderation') {
    $entity_type_manager = \Drupal::entityTypeManager();
    foreach ($entity_type_manager->getDefinitions() as $id => $entity_type) {
      if ($entity_type->getBundleOf()) {
        $storage = $entity_type_manager->getStorage($id);

        /** @var \Drupal\Core\Config\Entity\ConfigEntityInterface $bundle */
        foreach ($storage->loadMultiple() as $bundle) {
          $bundle
            ->unsetThirdPartySetting('workbench_moderation', 'enabled')
            ->unsetThirdPartySetting('workbench_moderation', 'allowed_moderation_states')
            ->unsetThirdPartySetting('workbench_moderation', 'default_moderation_state');
          $storage->save($bundle);
        }
      }
    }
  }
  \Drupal::logger('wbm_to_cm')->notice("workbench_moderation uninstalled");
}
