project:
  machine_name: capitalcamp
  prefix: DGC
  human_name: 'Drupal GovCon'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes:
    - 'capitalcamp@svn-6971.prod.hosting.acquia.com:capitalcamp.git'
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: capitalcamp.local
    ci: self
  default_alias: '${drush.aliases.local}'
target-hooks:
  frontend-setup:
    dir: '${docroot}/themes/custom/twentyseventeen'
    command: 'npm run install-tools'
  frontend-build:
    dir: '${docroot}/themes/custom/twentyseventeen'
    command: 'npm run build'
  pre-config-import:
    dir: '${docroot}'
    command: 'echo ''No pre-config-import configured.'''
  post-deploy-build:
    dir: '${deploy.dir}/docroot/profiles/contrib/lightning'
    command: 'echo ''No post-setup-build hook configured.'''
  post-setup-build:
    dir: '${docroot}/profiles/contrib/lightning'
    command: 'echo ''No post-setup-build hook configured.'''
import: '${repo.root}/blt/custom.xml'
modules:
  local:
    enable: {  }
    uninstall: {  }
  ci:
    enable: {  }
    uninstall: {  }
  dev:
    enable: {  }
    uninstall: {  }
  test:
    enable: {  }
    uninstall: {  }
  prod:
    enable: {  }
    uninstall: {  }
behat:
  paths:
    - '${repo.root}/tests/behat'

