<?php

/**
 * @file
 * Contains install and update functions for CapitalCamp.
 */

use Drupal\taxonomy\Entity\Term;
use Drupal\webform\Entity\Webform;
use Drupal\webform\Entity\WebformSubmission;

/**
 * Implements hook_install().
 */
function capitalcamp_testing_install() {
  $yearTerms = [
    '2019',
    '2020',
  ];
  foreach ($yearTerms as $year) {
    Term::create([
      'name' => $year,
      'vid' => 'conference_year',
    ])->save();
  }

  $sessionTerms = [
    'Backend',
    'Community',
    'Content',
    'Keynote',
    'UX',
  ];
  foreach ($sessionTerms as $session) {
    Term::create([
      'name' => $session,
      'vid' => 'session_track',
      'field_conference_year' => 2020,
    ])->save();
  }

  $webform_id = '2020_registration';
  $webform = Webform::load($webform_id);
  // Create webform submission.
  $values = [
    'webform_id' => $webform->id(),
    'data' => [
      'name' => 'Test User',
      'email' => 'no-reply@acquia.com',
      'ticket_status' => 'Ticket',
    ],
  ];

  /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
  $webform_submission = WebformSubmission::create($values);
  $webform_submission->save();
}
