_core:
  default_config_hash: yHBuI_J_kdrugm0JRNsxHODZ0qQyPzejI6r1ZPacK5Q
shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: ''
    pass: ''
allow_cli: true
debug_header: false
unset_basic_auth_headers: true
print: 'Please provide credentials to access non-prod environment.'
method: 0
paths: ''
allowlist: ''
http_method_allowlist: {  }
domains: ''
path: ''
